server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bvs
    username: root
    password: root
  mvc:
    # 抛出404异常
    throw-exception-if-no-handler-found: true
  web:
    resources:
      # 禁用映射
      add-mappings: false